{% set name = "nrel-rex" %}
{% set version = "0.2.89" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NREL/rex/archive/v{{ version }}.tar.gz
  sha256: 5cbf900ff56a39438fe207d31c2aa5a6bd5af30ca958140f3c8edb1ee9ead595

build:
  entry_points:
    - rex=rex.resource_extraction.resource_cli:main
    - NSRDBX=rex.resource_extraction.nsrdb_cli:main
    - WINDX=rex.resource_extraction.wind_cli:main
    - WaveX=rex.resource_extraction.wave_cli:main
    - MultiYearX=rex.resource_extraction.multi_year_resource_cli:main
    - US-wave=rex.resource_extraction.US_wave_cli:main
    - rechunk=rex.rechunk_h5.rechunk_cli:main
    - combine-h5=rex.rechunk_h5.combine_h5_cli:main
    - temporal-stats=rex.temporal_stats.temporal_stats_cli:main
    - wind-rose=rex.joint_pd.wind_rose_cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - click >=7.0
    - h5py >=2.10.0,!=3.0.0
    - h5pyd >=0.7.0
    - numpy >=1.16
    - pandas >=2.0
    - psutil >=5.6
    - pyyaml
    - scipy >=1.3
    - toml >=0.10.0
    - packaging

test:
  imports:
    - rex
  commands:
    - pip check
    - rex --help
    - NSRDBX --help
    - WINDX --help
    - WaveX --help
    - MultiYearX --help
    - US-wave --help
    - rechunk --help
    - combine-h5 --help
    - temporal-stats --help
  requires:
    - pip

about:
  home: https://nrel.github.io/rex/
  summary: "National Renewable Energy Laboratory's (NREL's) REsource eXtraction tool: rex"
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ssolson
